import { useState, useEffect } from 'react'
import Link from 'next/link'
import Head from 'next/head'
import { fetchBicycles } from "../services/frontend/bicycle_service"
import styles from '../styles/BicycleList.module.css'
import Header from '../components/header'

export default function BicycleList() {
  const [bicycles, setBicycles] = useState([]);

  useEffect(() => {
    fetchBicycles().then(data => {
      setBicycles(data.data);
    });
  }, []);

  return (
    <div id={styles.bicycleListContainer}>
      <Head>
        <title>Bicycles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <div className={styles.bicycleListCards}>
        {bicycles.map((bicycle, index) =>
          <div className={styles.bicycleListCard} key={bicycle.id}>
            <p>{bicycle.brand}</p>
            <p>{bicycle.model}</p>
          </div>)
        }
      </div>
    </div>
  )
}