import { useState, useEffect } from 'react'
import Link from 'next/link'
import Head from 'next/head'
import { fetchBicycles, deleteBicycle } from "../services/frontend/bicycle_service"
import styles from '../styles/BicycleList.module.css'
import Header from '../components/header'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTrash } from '@fortawesome/free-solid-svg-icons'

export default function BicycleList() {
  const [bicycles, setBicycles] = useState([]);

  useEffect(() => {
    findAllBicycles();
  }, []);

  const findAllBicycles = () => {
    fetchBicycles().then(data => {
      setBicycles(data.data);
    });
  }

  const handleDelete = (id) => {
    deleteBicycle(id).then(() => {
      findAllBicycles();
    })
  }

  return (
    <div id={styles.bicycleListContainer}>
      <Head>
        <title>Bicycles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className={styles.bicycleListCards}>
        {bicycles.map((bicycle, index) =>
          <div className={styles.bicycleListCard} key={bicycle.id}>
            <p>{bicycle.brand} {bicycle.model}</p>
            <FontAwesomeIcon icon={faTrash} className={styles.bicycleListTrashIcon}
              onClick={() => handleDelete(bicycle.id)} />
          </div>)
        }
      </div>
    </div>
  )
}