import { FormEvent, useState } from 'react'
import Head from 'next/head'
import { createBicycle } from '../services/frontend/bicycle_service'
import styles from '../styles/BicycleAdd.module.css'
import Header from '../components/header'

export default function BicycleAdd() {

  const [state, setState] = useState({
    brand: "",
    model: ""
  });

  function handleChange(e) {
    setState({ ...state, [e.target.name]: e.target.value });
  }

  async function handleSubmit(e) {
    e.preventDefault();

    const data = {
      brand: state.brand,
      model: state.model
    }

    await createBicycle(data)
      .then(({ data }) => {
        window.location.href = "/bicycle_list";
      })
      .catch((e) => {
        window.location.href = "/bicycle_add";
      });
  }

  return (
    <div id={styles.bicycleAddContainer}>
      <Head>
        <title>Bicycles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div id={styles.bicycleFormContainer}>
        <h1>Creating new bicycle...</h1>
        <form onSubmit={handleSubmit}>
          <label htmlFor="brand">Brand:</label>
          <input className={styles.bicycleFormInput}
            id="brand"
            name="brand"
            type="text"
            placeholder="Enter brand"
            onChange={handleChange}
            value={state.brand}
            required
          />
          <label htmlFor="model">Model:</label>
          <input className={styles.bicycleFormInput}
            id="model"
            name="model"
            type="text"
            placeholder="Enter model"
            onChange={handleChange}
            value={state.model}
            required
          />
          <button type="submit">Add Bicycle</button>
        </form>
      </div>
    </div>
  );
}