import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header'


export default function Home() {

  const handleSubmit = (e) => {
    e.preventDefault();
    window.location.href = "/bicycle_list";
  }

  return (
    <div id={styles.bicycleHomeContainer}>
      <Head>
        <title>Bicycles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div id={styles.bicycleHomeDataContainer}>
        <h1>An Example App to start working with Next.js...</h1>
        <form onSubmit={handleSubmit}>
          <button type="submit">Let's start!</button>
        </form>
      </div>
    </div>
  )
}
